# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/andres6936/Clion-2018.3.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/andres6936/Clion-2018.3.4/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andres6936/CLionProjects/BearLibTerminal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andres6936/CLionProjects/BearLibTerminal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/andres6936/Clion-2018.3.4/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/andres6936/Clion-2018.3.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andres6936/CLionProjects/BearLibTerminal/CMakeFiles /home/andres6936/CLionProjects/BearLibTerminal/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andres6936/CLionProjects/BearLibTerminal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BearLibTerminal

# Build rule for target.
BearLibTerminal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BearLibTerminal
.PHONY : BearLibTerminal

# fast build rule for target.
BearLibTerminal/fast:
	$(MAKE) -f Terminal/CMakeFiles/BearLibTerminal.dir/build.make Terminal/CMakeFiles/BearLibTerminal.dir/build
.PHONY : BearLibTerminal/fast

#=============================================================================
# Target rules for targets named freetype2

# Build rule for target.
freetype2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freetype2
.PHONY : freetype2

# fast build rule for target.
freetype2/fast:
	$(MAKE) -f Terminal/Dependencies/FreeType/CMakeFiles/freetype2.dir/build.make Terminal/Dependencies/FreeType/CMakeFiles/freetype2.dir/build
.PHONY : freetype2/fast

#=============================================================================
# Target rules for targets named picopng

# Build rule for target.
picopng: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 picopng
.PHONY : picopng

# fast build rule for target.
picopng/fast:
	$(MAKE) -f Terminal/Dependencies/PicoPNG/CMakeFiles/picopng.dir/build.make Terminal/Dependencies/PicoPNG/CMakeFiles/picopng.dir/build
.PHONY : picopng/fast

#=============================================================================
# Target rules for targets named SampleOmni

# Build rule for target.
SampleOmni: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SampleOmni
.PHONY : SampleOmni

# fast build rule for target.
SampleOmni/fast:
	$(MAKE) -f Samples/Omni/CMakeFiles/SampleOmni.dir/build.make Samples/Omni/CMakeFiles/SampleOmni.dir/build
.PHONY : SampleOmni/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... BearLibTerminal"
	@echo "... freetype2"
	@echo "... picopng"
	@echo "... SampleOmni"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

